version: 2
executorType: docker
containerInfo:
  - image: markfirmware/torodocker:torodocker-1500629424965
stages:
  build:
    workDir: ~/ToroKernel
    steps:
      - type: checkout
      - run: cd markfirmware
      - run: ./linux-testelf.sh
      - name: Save artifacts
        type: artifacts-store
        path: artifacts
        destination: testelf
